import type { Account, Budget, Transaction } from './types';
import { subDays } from 'date-fns';

export const accounts: Account[] = [
  { id: 'acc_1', name: 'Checking Account', type: 'checking', balance: 5230.5 },
  { id: 'acc_2', name: 'Savings Account', type: 'savings', balance: 15820.75 },
  { id: 'acc_3', name: 'Visa Credit Card', type: 'credit-card', balance: -890.21 },
  { id: 'acc_4', name: 'Cash Wallet', type: 'cash', balance: 340.0 },
];

export const transactions: Transaction[] = [
  {
    id: 'txn_1',
    date: subDays(new Date(), 1).toISOString(),
    description: 'Starbucks Coffee',
    amount: 5.75,
    type: 'expense',
    category: 'Food & Drink',
    accountId: 'acc_3',
  },
  {
    id: 'txn_2',
    date: subDays(new Date(), 1).toISOString(),
    description: 'Monthly Salary',
    amount: 4500,
    type: 'income',
    category: 'Salary',
    accountId: 'acc_1',
  },
  {
    id: 'txn_3',
    date: subDays(new Date(), 2).toISOString(),
    description: 'Groceries from Whole Foods',
    amount: 154.32,
    type: 'expense',
    category: 'Groceries',
    accountId: 'acc_3',
  },
  {
    id: 'txn_4',
    date: subDays(new Date(), 3).toISOString(),
    description: 'Netflix Subscription',
    amount: 15.99,
    type: 'expense',
    category: 'Subscriptions',
    accountId: 'acc_3',
  },
  {
    id: 'txn_5_exp',
    date: subDays(new Date(), 4).toISOString(),
    description: 'Transfer to Savings',
    amount: 1000,
    type: 'expense',
    category: 'Transfers',
    accountId: 'acc_1',
    transferId: 'transfer_1',
  },
  {
    id: 'txn_5_inc',
    date: subDays(new Date(), 4).toISOString(),
    description: 'Transfer to Savings',
    amount: 1000,
    type: 'income',
    category: 'Transfers',
    accountId: 'acc_2',
    transferId: 'transfer_1',
  },
  {
    id: 'txn_6',
    date: subDays(new Date(), 5).toISOString(),
    description: 'Dinner at Italian Restaurant',
    amount: 85.5,
    type: 'expense',
    category: 'Restaurants',
    accountId: 'acc_3',
  },
  {
    id: 'txn_7',
    date: subDays(new Date(), 6).toISOString(),
    description: 'Gasoline',
    amount: 55.20,
    type: 'expense',
    category: 'Transportation',
    accountId: 'acc_1',
  },
  {
    id: 'txn_8',
    date: subDays(new Date(), 8).toISOString(),
    description: 'Freelance Project Payment',
    amount: 750,
    type: 'income',
    category: 'Freelance',
    accountId: 'acc_1',
  },
  {
    id: 'txn_9',
    date: subDays(new Date(), 10).toISOString(),
    description: 'Amazon Purchase',
    amount: 42.10,
    type: 'expense',
    category: 'Shopping',
    accountId: 'acc_3',
  },
  {
    id: 'txn_10',
    date: subDays(new Date(), 15).toISOString(),
    description: 'Gym Membership',
    amount: 49.99,
    type: 'expense',
    category: 'Health & Fitness',
    accountId: 'acc_3',
  },
  {
    id: 'txn_11',
    date: subDays(new Date(), 18).toISOString(),
    description: 'Movie Tickets',
    amount: 32.00,
    type: 'expense',
    category: 'Entertainment',
    accountId: 'acc_3',
  },
  {
    id: 'txn_12',
    date: subDays(new Date(), 20).toISOString(),
    description: 'Groceries from Trader Joe\'s',
    amount: 98.75,
    type: 'expense',
    category: 'Groceries',
    accountId: 'acc_1',
  },
  {
    id: 'txn_13',
    date: subDays(new Date(), 22).toISOString(),
    description: 'Electricity Bill',
    amount: 75.60,
    type: 'expense',
    category: 'Utilities',
    accountId: 'acc_1',
  },
  {
    id: 'txn_14',
    date: subDays(new Date(), 25).toISOString(),
    description: 'Lunch with colleagues',
    amount: 25.40,
    type: 'expense',
    category: 'Restaurants',
    accountId: 'acc_4',
  },
  {
    id: 'txn_15',
    date: subDays(new Date(), 28).toISOString(),
    description: 'New Book',
    amount: 18.99,
    type: 'expense',
    category: 'Shopping',
    accountId: 'acc_3',
  },
];


export const budgets: Budget[] = [
  { id: 'bud_1', category: 'Groceries', amount: 500, spent: 253.07 },
  { id: 'bud_2', category: 'Restaurants', amount: 200, spent: 110.9 },
  { id: 'bud_3', category: 'Shopping', amount: 300, spent: 61.09 },
  { id: 'bud_4', category: 'Transportation', amount: 150, spent: 55.2 },
  { id: 'bud_5', category: 'Entertainment', amount: 100, spent: 150.00 }, // Overspent
];
